name: Auto update contents

permissions:
      contents: read
      pull-requests: write

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'events/tournaments/**.txt'
  schedule:
    - cron: "24 7 * * 1"
    - cron: "27 7 * * 4"

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  updates:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.TOKEN }}
      - name: Setup Python '3.11'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update contents
        run: |
          python3 python/api2md.py
          python3 python/cttq.py
          python3 python/md2html_tournaments.py
          python3 python/md2html_bestplayers.py
          python3 python/update_time.py
      - name: Commit & Push
        run: |
          git config --local user.email ""
          git config --local user.name "Thí Vua Lấy Tốt"
          git add -A
          git commit -m "Update contents"
          git push --force
